name: Quality Control

on: [push, pull_request]

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: argent-playground
    steps:
      - name: Checkout playground
        uses: actions/checkout@v6
        with:
          path: argent-playground

      - name: Checkout Argent
        uses: actions/checkout@v6
        with:
          repository: michaelsutton/argent
          ref: master
          path: argent

      - name: Checkout Silverscript
        uses: actions/checkout@v6
        with:
          repository: michaelsutton/silverscript
          ref: 513c62a04671aa2bba5558b70982dabdb2c18da0
          path: silverscript

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.94.0
          components: rustfmt, clippy

      - name: Run checks
        run: ./check.sh

      - name: Run chess checks
        working-directory: argent-playground/chess
        run: ./check.sh

      - name: Verify working tree
        run: git diff --exit-code
